name: Terraform Checks
on:
  push:
    branches: [ main ]
#  pull_request:

jobs:
  terraform-checks:
    name: Terraform Validate, Init and Plan
    runs-on: ubuntu-latest
    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gcloud
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Format
        uses: dflook/terraform-fmt-check@v1
        with:
          actions_subcommand: fmt

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
          tf_actions_version: 1.3.6
          tf_actions_working_dir: ./example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}

      - name: Terraform validate
        uses: dflook/terraform-validate@v1
        with:
          tf_actions_working_dir: ./example

      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          cd ./example
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
          fi
            echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi